name: Run examples
on:
  pull_request:
    paths:
      - '.github/workflows/go-examples.yml'
      - '**.go'
jobs:
  examples:
    name: Run goptuna examples on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: Running go tests
      env:
        GO111MODULE: on
      run: |
        make build
        ./bin/cmaes
        ./bin/cmaes_blackhole
        ./bin/simple_tpe
        ./bin/concurrency
        ./bin/trialnotify
