name: lint-typescript
on:
  pull_request:
    paths:
      - '.github/workflows/run-typescript-lints.yml'
      - '**.ts'
      - '**.tsx'
jobs:
  lint:
    name: Lint checking on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Set up Node v14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: |
          cd dashboard
          npm install
          npm run build:prd
